name: chitti_finserve_lead_app

description: >-
  Chitti Finserve Loan Lead Generation App with dynamic content, clean architecture, and Riverpod state management.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.6
  http: ^1.1.0

  # For file picker and image upload (future use)
  file_picker: ^10.2.0
  image_picker: ^1.1.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.5
  
  # UI Enhancement packages
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  flutter_staggered_animations: ^1.1.1
  animated_text_kit: ^4.2.2
  
  # Local storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/
    - assets/animations/
